name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: workflow-release
    steps:
#      - uses: actions/checkout@v3  # MAYBE: remove
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.WORKFLOW_RELEASE_TOKEN }}
